server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/math
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
