server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/math
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
